
# Generated by crate2nix 0.3.0-beta.0 with the command:
#   "generate"
# See https://github.com/kolloch/crate2nix for more info.

{ pkgs? import <nixpkgs> { config = {}; },
  lib? pkgs.lib,
  callPackage? pkgs.callPackage,
  stdenv? pkgs.stdenv,
  buildRustCrate? pkgs.buildRustCrate,
  fetchurl? pkgs.fetchurl }:

rec {
    #
    # "public" attributes that we attempt to keep stable with new versions of crate2nix.
    #

    # Use this attribute to refer to the derivation building your root crate.
    root_crate = crates."crate2nix-test 0.1.0 (path+file:///home/ed/git/crate2nix-test)";
    # Refer your crate build derivation by name here.
    workspace_members = {
        "crate2nix-test" = crates."crate2nix-test 0.1.0 (path+file:///home/ed/git/crate2nix-test)";
    };

    #
    # "private" attributes that may change in every new version of crate2nix.
    #

    crates = {
        "autocfg 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "autocfg";
                version = "0.1.2";
                edition = "2015";
                sha256 = "0dv81dwnp1al3j4ffz007yrjv4w1c7hw09gnf0xs3icxiw6qqfs3";
                libPath = "src/lib.rs";
                authors = [
                    "Josh Stone <cuviper@gmail.com>"
                ];
            };
        "bitflags 1.0.4 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "bitflags";
                version = "1.0.4";
                edition = "2015";
                sha256 = "1g1wmz2001qmfrd37dnd5qiss5njrw26aywmg6yhkmkbyrhjxb08";
                libPath = "src/lib.rs";
                authors = [
                    "The Rust Project Developers"
                ];
                features = [
                   "default"
                ];
            };
        "cfg-if 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "cfg-if";
                version = "0.1.7";
                edition = "2015";
                sha256 = "13gvcx1dxjq4mpmpj26hpg3yc97qffkx2zi58ykr1dwr8q2biiig";
                libPath = "src/lib.rs";
                authors = [
                    "Alex Crichton <alex@alexcrichton.com>"
                ];
            };
        "cloudabi 0.0.3 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "cloudabi";
                version = "0.0.3";
                edition = "2015";
                sha256 = "1z9lby5sr6vslfd14d6igk03s7awf91mxpsfmsp3prxbxlk0x7h5";
                libPath = "cloudabi.rs";
                authors = [
                    "Nuxi (https://nuxi.nl/) and contributors"
                ];
                dependencies = filterDeps [
                    "bitflags 1.0.4 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                features = [
                   "bitflags"
                   "default"
                ];
            };
        "crate2nix-test 0.1.0 (path+file:///home/ed/git/crate2nix-test)"
            = buildRustCrate {
                crateName = "crate2nix-test";
                version = "0.1.0";
                edition = "2018";
                src = (builtins.filterSource sourceFilter ./.);
                authors = [
                    "Ed Cragg <drq.11235@gmail.com>"
                ];
                dependencies = filterDeps [
                    "html5ever 0.22.5 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "fuchsia-cprng 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "fuchsia-cprng";
                version = "0.1.1";
                edition = "2018";
                sha256 = "07apwv9dj716yjlcj29p94vkqn5zmfh7hlrqvrjx3wzshphc95h9";
                libPath = "src/lib.rs";
                authors = [
                    "Erick Tryzelaar <etryzelaar@google.com>"
                ];
            };
        "futf 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "futf";
                version = "0.1.4";
                edition = "2015";
                sha256 = "0sf664dbha0iwgqbpa1nhvssm3xi9z07mz90m9bfipgdybbs1pbn";
                libPath = "src/lib.rs";
                authors = [
                    "Keegan McAllister <kmcallister@mozilla.com>"
                ];
                dependencies = filterDeps [
                    "mac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
                    "new_debug_unreachable 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "html5ever 0.22.5 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "html5ever";
                version = "0.22.5";
                edition = "2015";
                sha256 = "1hbkxvy4za50y78h1dv6h75cpj83iwg6df94nyj003j7nvq5zchf";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "The html5ever Project Developers"
                ];
                dependencies = filterDeps [
                    "log 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)"
                    "mac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
                    "markup5ever 0.7.5 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                buildDependencies = filterDeps [
                    "proc-macro2 0.4.27 (registry+https://github.com/rust-lang/crates.io-index)"
                    "quote 0.6.12 (registry+https://github.com/rust-lang/crates.io-index)"
                    "syn 0.15.32 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "itoa 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "itoa";
                version = "0.4.3";
                edition = "2015";
                sha256 = "0zadimmdgvili3gdwxqg7ljv3r4wcdg1kkdfp9nl15vnm23vrhy1";
                libPath = "src/lib.rs";
                authors = [
                    "David Tolnay <dtolnay@gmail.com>"
                ];
                features = [
                   "default"
                   "std"
                ];
            };
        "lazy_static 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "lazy_static";
                version = "1.3.0";
                edition = "2015";
                sha256 = "1vv47va18ydk7dx5paz88g3jy1d3lwbx6qpxkbj8gyfv770i4b1y";
                libPath = "src/lib.rs";
                authors = [
                    "Marvin Löbel <loebel.marvin@gmail.com>"
                ];
            };
        "libc 0.2.51 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "libc";
                version = "0.2.51";
                edition = "2015";
                sha256 = "1lzavxj1ymm7vghs6nmzq9shprdlqby73py9k30gwvv0dwy365cv";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "The Rust Project Developers"
                ];
                features = [
                   "default"
                   "use_std"
                ];
            };
        "log 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "log";
                version = "0.4.6";
                edition = "2015";
                sha256 = "1nd8dl9mvc9vd6fks5d4gsxaz990xi6rzlb8ymllshmwi153vngr";
                libPath = "src/lib.rs";
                authors = [
                    "The Rust Project Developers"
                ];
                dependencies = filterDeps [
                    "cfg-if 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "mac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "mac";
                version = "0.1.1";
                edition = "2015";
                sha256 = "17fq2w1q33swr37dvpdc50xiaslym2jak4jrix83a075kk18c8fm";
                libPath = "src/lib.rs";
                authors = [
                    "Jonathan Reem <jonathan.reem@gmail.com>"
                ];
            };
        "markup5ever 0.7.5 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "markup5ever";
                version = "0.7.5";
                edition = "2015";
                sha256 = "039m4lsyhnma1jkrjlk8rwqhmvc1jgbs8dskqn16gc2yr5f6ji2k";
                build = "build.rs";
                libPath = "lib.rs";
                authors = [
                    "The html5ever Project Developers"
                ];
                dependencies = filterDeps [
                    "phf 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                    "string_cache 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)"
                    "tendril 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                buildDependencies = filterDeps [
                    "phf_codegen 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                    "serde 1.0.90 (registry+https://github.com/rust-lang/crates.io-index)"
                    "serde_derive 1.0.90 (registry+https://github.com/rust-lang/crates.io-index)"
                    "serde_json 1.0.39 (registry+https://github.com/rust-lang/crates.io-index)"
                    "string_cache_codegen 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "new_debug_unreachable 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "new_debug_unreachable";
                version = "1.0.3";
                edition = "2015";
                sha256 = "1lxbd0n9gwvzg41bxiij0c28g1sp1jhp4h1rh10qisc8viyhsdj0";
                libPath = "src/lib.rs";
                authors = [
                    "Matt Brubeck <mbrubeck@limpet.net>"
                    "Jonathan Reem <jonathan.reem@gmail.com>"
                ];
            };
        "phf 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "phf";
                version = "0.7.24";
                edition = "2015";
                sha256 = "19mmhmafd1dhywc7pzkmd1nq0kjfvg57viny20jqa91hhprf2dv5";
                libPath = "src/lib.rs";
                authors = [
                    "Steven Fackler <sfackler@gmail.com>"
                ];
                dependencies = filterDeps [
                    "phf_shared 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "phf_codegen 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "phf_codegen";
                version = "0.7.24";
                edition = "2015";
                sha256 = "0avkx97r4ph8rv70wwgniarlcfiq27yd74gmnxfdv3rx840cyf8g";
                libPath = "src/lib.rs";
                authors = [
                    "Steven Fackler <sfackler@gmail.com>"
                ];
                dependencies = filterDeps [
                    "phf_generator 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                    "phf_shared 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "phf_generator 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "phf_generator";
                version = "0.7.24";
                edition = "2015";
                sha256 = "1frn2jfydinifxb1fki0xnnsxf0f1ciaa79jz415r5qhw1ash72j";
                libPath = "src/lib.rs";
                authors = [
                    "Steven Fackler <sfackler@gmail.com>"
                ];
                dependencies = filterDeps [
                    "phf_shared 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                    "rand 0.6.5 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "phf_shared 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "phf_shared";
                version = "0.7.24";
                edition = "2015";
                sha256 = "1hndqn461jvm2r269ym4qh7fnjc6n8yy53avc2pb43p70vxhm9rl";
                libPath = "src/lib.rs";
                authors = [
                    "Steven Fackler <sfackler@gmail.com>"
                ];
                dependencies = filterDeps [
                    "siphasher 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "precomputed-hash 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "precomputed-hash";
                version = "0.1.1";
                edition = "2015";
                sha256 = "1x37xiarlc39772glsrbb9ic5cpaky4q0fi0ax42bwwrn4jfqgyj";
                libPath = "src/lib.rs";
                authors = [
                    "Emilio Cobos Álvarez <emilio@crisal.io>"
                ];
            };
        "proc-macro2 0.4.27 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "proc-macro2";
                version = "0.4.27";
                edition = "2015";
                sha256 = "1cp4c40p3hwn2sz72ssqa62gp5n8w4gbamdqvvadzp5l7gxnq95i";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "Alex Crichton <alex@alexcrichton.com>"
                ];
                dependencies = filterDeps [
                    "unicode-xid 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                features = [
                   "default"
                   "proc-macro"
                ];
            };
        "quote 0.6.12 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "quote";
                version = "0.6.12";
                edition = "2015";
                sha256 = "1ckd2d2sy0hrwrqcr47dn0n3hyh7ygpc026l8xaycccyg27mihv9";
                libPath = "src/lib.rs";
                authors = [
                    "David Tolnay <dtolnay@gmail.com>"
                ];
                dependencies = filterDeps [
                    "proc-macro2 0.4.27 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                features = [
                   "default"
                   "proc-macro"
                   "proc-macro2"
                ];
            };
        "rand 0.6.5 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand";
                version = "0.6.5";
                edition = "2015";
                sha256 = "0zbck48159aj8zrwzf80sd9xxh96w4f4968nshwjpysjvflimvgb";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                    "The Rust Project Developers"
                ];
                dependencies = filterDeps [
                    # target = "cfg(unix)"
                    (cfg target."unix" "libc 0.2.51 (registry+https://github.com/rust-lang/crates.io-index)")
                    "rand_chacha 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
                    "rand_core 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
                    "rand_hc 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
                    "rand_isaac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
                    "rand_jitter 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)"
                    "rand_os 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)"
                    "rand_pcg 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)"
                    "rand_xorshift 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
                    # target = "cfg(windows)"
                    (cfg target."windows" "winapi 0.3.7 (registry+https://github.com/rust-lang/crates.io-index)")
                ];
                buildDependencies = filterDeps [
                    "autocfg 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                features = [
                   "alloc"
                   "default"
                   "rand_core"
                   "rand_jitter"
                   "rand_os"
                   "std"
                ];
            };
        "rand_chacha 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_chacha";
                version = "0.1.1";
                edition = "2015";
                sha256 = "0xnxm4mjd7wjnh18zxc1yickw58axbycp35ciraplqdfwn1gffwi";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                    "The Rust Project Developers"
                ];
                dependencies = filterDeps [
                    "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                buildDependencies = filterDeps [
                    "autocfg 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_core";
                version = "0.3.1";
                edition = "2015";
                sha256 = "0q0ssgpj9x5a6fda83nhmfydy7a6c0wvxm0jhncsmjx8qp8gw91m";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                    "The Rust Project Developers"
                ];
                dependencies = filterDeps [
                    "rand_core 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "rand_core 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_core";
                version = "0.4.0";
                edition = "2015";
                sha256 = "0wb5iwhffibj0pnpznhv1g3i7h1fnhz64s3nz74fz6vsm3q6q3br";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                    "The Rust Project Developers"
                ];
                features = [
                   "alloc"
                   "std"
                ];
            };
        "rand_hc 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_hc";
                version = "0.1.0";
                edition = "2015";
                sha256 = "05agb75j87yp7y1zk8yf7bpm66hc0673r3dlypn0kazynr6fdgkz";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                ];
                dependencies = filterDeps [
                    "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "rand_isaac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_isaac";
                version = "0.1.1";
                edition = "2015";
                sha256 = "10hhdh5b5sa03s6b63y9bafm956jwilx41s71jbrzl63ccx8lxdq";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                    "The Rust Project Developers"
                ];
                dependencies = filterDeps [
                    "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "rand_jitter 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_jitter";
                version = "0.1.3";
                edition = "2015";
                sha256 = "1cb4q73rmh1inlx3liy6rabapcqh6p6c1plsd2lxw6dmi67d1qc3";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                ];
                dependencies = filterDeps [
                    # target = "cfg(any(target_os = \"macos\", target_os = \"ios\"))"
                    (cfg ((target."os" == "macos") || (target."os" == "ios")) "libc 0.2.51 (registry+https://github.com/rust-lang/crates.io-index)")
                    "rand_core 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
                    # target = "cfg(target_os = \"windows\")"
                    (cfg (target."os" == "windows") "winapi 0.3.7 (registry+https://github.com/rust-lang/crates.io-index)")
                ];
                features = [
                   "rand_core"
                   "std"
                ];
            };
        "rand_os 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_os";
                version = "0.1.3";
                edition = "2015";
                sha256 = "0ywwspizgs9g8vzn6m5ix9yg36n15119d6n792h7mk4r5vs0ww4j";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                ];
                dependencies = filterDeps [
                    # target = "cfg(target_os = \"cloudabi\")"
                    (cfg (target."os" == "cloudabi") "cloudabi 0.0.3 (registry+https://github.com/rust-lang/crates.io-index)")
                    # target = "cfg(target_os = \"fuchsia\")"
                    (cfg (target."os" == "fuchsia") "fuchsia-cprng 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)")
                    # target = "cfg(unix)"
                    (cfg target."unix" "libc 0.2.51 (registry+https://github.com/rust-lang/crates.io-index)")
                    "rand_core 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
                    # target = "cfg(target_env = \"sgx\")"
                    (cfg (target."env" == "sgx") "rdrand 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)")
                    # target = "cfg(windows)"
                    (cfg target."windows" "winapi 0.3.7 (registry+https://github.com/rust-lang/crates.io-index)")
                ];
            };
        "rand_pcg 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_pcg";
                version = "0.1.2";
                edition = "2015";
                sha256 = "04qgi2ai2z42li5h4aawvxbpnlqyjfnipz9d6k73mdnl6p1xq938";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                ];
                dependencies = filterDeps [
                    "rand_core 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                buildDependencies = filterDeps [
                    "autocfg 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "rand_xorshift 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rand_xorshift";
                version = "0.1.1";
                edition = "2015";
                sha256 = "0v365c4h4lzxwz5k5kp9m0661s0sss7ylv74if0xb4svis9sswnn";
                libPath = "src/lib.rs";
                authors = [
                    "The Rand Project Developers"
                    "The Rust Project Developers"
                ];
                dependencies = filterDeps [
                    "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "rdrand 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "rdrand";
                version = "0.4.0";
                edition = "2015";
                sha256 = "15hrcasn0v876wpkwab1dwbk9kvqwrb3iv4y4dibb6yxnfvzwajk";
                libPath = "src/lib.rs";
                authors = [
                    "Simonas Kazlauskas <rdrand@kazlauskas.me>"
                ];
                dependencies = filterDeps [
                    "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                features = [
                   "default"
                   "std"
                ];
            };
        "ryu 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "ryu";
                version = "0.2.7";
                edition = "2015";
                sha256 = "0m8szf1m87wfqkwh1f9zp9bn2mb0m9nav028xxnd0hlig90b44bd";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "David Tolnay <dtolnay@gmail.com>"
                ];
            };
        "serde 1.0.90 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "serde";
                version = "1.0.90";
                edition = "2015";
                sha256 = "10b6n74m1dvb667vrn1db47ncb4h0mkqbg1dsamqjvv5vl5b5j56";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "Erick Tryzelaar <erick.tryzelaar@gmail.com>"
                    "David Tolnay <dtolnay@gmail.com>"
                ];
                features = [
                   "default"
                   "std"
                ];
            };
        "serde_derive 1.0.90 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "serde_derive";
                version = "1.0.90";
                edition = "2015";
                sha256 = "1m4xgyl8jj3mxj0wszminzc1qf2gbkj9dpl17vi95nwl6m7i157y";
                procMacro = true;
                authors = [
                    "Erick Tryzelaar <erick.tryzelaar@gmail.com>"
                    "David Tolnay <dtolnay@gmail.com>"
                ];
                dependencies = filterDeps [
                    "proc-macro2 0.4.27 (registry+https://github.com/rust-lang/crates.io-index)"
                    "quote 0.6.12 (registry+https://github.com/rust-lang/crates.io-index)"
                    "syn 0.15.32 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                features = [
                   "default"
                ];
            };
        "serde_json 1.0.39 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "serde_json";
                version = "1.0.39";
                edition = "2015";
                sha256 = "07ydv06hn8x0yl0rc94l2wl9r2xz1fqd97n1s6j3bgdc6gw406a8";
                libPath = "src/lib.rs";
                authors = [
                    "Erick Tryzelaar <erick.tryzelaar@gmail.com>"
                    "David Tolnay <dtolnay@gmail.com>"
                ];
                dependencies = filterDeps [
                    "itoa 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)"
                    "ryu 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)"
                    "serde 1.0.90 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                features = [
                   "default"
                ];
            };
        "siphasher 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "siphasher";
                version = "0.2.3";
                edition = "2015";
                sha256 = "1ganj1grxqnkvv4ds3vby039bm999jrr58nfq2x3kjhzkw2bnqkw";
                libPath = "src/lib.rs";
                authors = [
                    "Frank Denis <github@pureftpd.org>"
                ];
            };
        "string_cache 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "string_cache";
                version = "0.7.3";
                edition = "2015";
                sha256 = "1z2995v9m7cbz84b8bwpz25xgskq1a7kzsv467zn6fm5gdj8jzh0";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "The Servo Project Developers"
                ];
                dependencies = filterDeps [
                    "lazy_static 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)"
                    "new_debug_unreachable 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)"
                    "phf_shared 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                    "precomputed-hash 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
                    "serde 1.0.90 (registry+https://github.com/rust-lang/crates.io-index)"
                    "string_cache_shared 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                buildDependencies = filterDeps [
                    "string_cache_codegen 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "string_cache_codegen 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "string_cache_codegen";
                version = "0.4.2";
                edition = "2015";
                sha256 = "1y4fmlxqilijdvbsfr2z98paggfj9fpsyaq50v0p0vd9755z791i";
                libPath = "lib.rs";
                authors = [
                    "The Servo Project Developers"
                ];
                dependencies = filterDeps [
                    "phf_generator 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                    "phf_shared 0.7.24 (registry+https://github.com/rust-lang/crates.io-index)"
                    "proc-macro2 0.4.27 (registry+https://github.com/rust-lang/crates.io-index)"
                    "quote 0.6.12 (registry+https://github.com/rust-lang/crates.io-index)"
                    "string_cache_shared 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "string_cache_shared 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "string_cache_shared";
                version = "0.3.0";
                edition = "2015";
                sha256 = "0yc59f5npg4ip56aha03yzc7nxgl7c31hv6kq7zrx7rvs3h1cb8j";
                libPath = "lib.rs";
                authors = [
                    "The Servo Project Developers"
                ];
            };
        "syn 0.15.32 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "syn";
                version = "0.15.32";
                edition = "2015";
                sha256 = "1xq1mbns8zyg2ls5927wqi7i7hn2y933czbqqds648gcdqccsqb0";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "David Tolnay <dtolnay@gmail.com>"
                ];
                dependencies = filterDeps [
                    "proc-macro2 0.4.27 (registry+https://github.com/rust-lang/crates.io-index)"
                    "quote 0.6.12 (registry+https://github.com/rust-lang/crates.io-index)"
                    "unicode-xid 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
                features = [
                   "clone-impls"
                   "default"
                   "derive"
                   "extra-traits"
                   "fold"
                   "full"
                   "parsing"
                   "printing"
                   "proc-macro"
                   "proc-macro2"
                   "quote"
                   "visit"
                ];
            };
        "tendril 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "tendril";
                version = "0.4.1";
                edition = "2015";
                sha256 = "02k6iwlyqd3xvjvi50l6n5yspmcf4rkhs6b49h3a1d6kr4ydmydm";
                libPath = "src/lib.rs";
                authors = [
                    "Keegan McAllister <mcallister.keegan@gmail.com>"
                    "Simon Sapin <simon.sapin@exyr.org>"
                    "Chris Morgan <me@chrismorgan.info>"
                ];
                dependencies = filterDeps [
                    "futf 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)"
                    "mac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)"
                    "utf-8 0.7.5 (registry+https://github.com/rust-lang/crates.io-index)"
                ];
            };
        "unicode-xid 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "unicode-xid";
                version = "0.1.0";
                edition = "2015";
                sha256 = "05wdmwlfzxhq3nhsxn6wx4q8dhxzzfb9szsz6wiw092m1rjj01zj";
                libPath = "src/lib.rs";
                authors = [
                    "erick.tryzelaar <erick.tryzelaar@gmail.com>"
                    "kwantam <kwantam@gmail.com>"
                ];
                features = [
                   "default"
                ];
            };
        "utf-8 0.7.5 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "utf-8";
                version = "0.7.5";
                edition = "2015";
                sha256 = "02y7d0ch5zfdy0mailqfb14vcbhr7kw1nsfrs0q9c4bq5g9c10qp";
                libPath = "src/lib.rs";
                authors = [
                    "Simon Sapin <simon.sapin@exyr.org>"
                ];
            };
        "winapi 0.3.7 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "winapi";
                version = "0.3.7";
                edition = "2015";
                sha256 = "1k51gfkp0zqw7nj07y443mscs46icmdhld442s2073niap0kkdr8";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "Peter Atashian <retep998@gmail.com>"
                ];
                dependencies = filterDeps [
                    # target = "i686-pc-windows-gnu"
                    (cfg (stdenv.hostPlatform.config == "i686-pc-windows-gnu") "winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)")
                    # target = "x86_64-pc-windows-gnu"
                    (cfg (stdenv.hostPlatform.config == "x86_64-pc-windows-gnu") "winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)")
                ];
                features = [
                   "minwindef"
                   "ntsecapi"
                   "profileapi"
                   "winnt"
                ];
            };
        "winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "winapi-i686-pc-windows-gnu";
                version = "0.4.0";
                edition = "2015";
                sha256 = "05ihkij18r4gamjpxj4gra24514can762imjzlmak5wlzidplzrp";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "Peter Atashian <retep998@gmail.com>"
                ];
            };
        "winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)"
            = buildRustCrate {
                crateName = "winapi-x86_64-pc-windows-gnu";
                version = "0.4.0";
                edition = "2015";
                sha256 = "0n1ylmlsb8yg1v583i4xy0qmqg42275flvbc51hdqjjfjcl9vlbj";
                build = "build.rs";
                libPath = "src/lib.rs";
                authors = [
                    "Peter Atashian <retep998@gmail.com>"
                ];
            };
    };

    # Target (platform) data for conditional dependencies.
    # This corresponds to what buildRustCrate is setting.
    target = {
        unix = true;
        windows = false;

        # This doesn't appear to be officially documented anywhere yet.
        # See https://github.com/rust-lang-nursery/rust-forge/issues/101.
        os = if stdenv.hostPlatform.isDarwin
          then "macos"
          else stdenv.hostPlatform.parsed.kernel.name;
        arch = stdenv.hostPlatform.parsed.cpu.name;
        family = "unix";
        env = "gnu";
        endian = if stdenv.hostPlatform.parsed.cpu.significantByte.name == "littleEndian" then "little" else "big";
        pointer_width = toString stdenv.hostPlatform.parsed.cpu.bits;
        vendor = stdenv.hostPlatform.parsed.vendor.name;
        debug_assertions = false;
     };

    # Utility functions

    # Filter null package_ids and map the IDs to crate derivations.
    filterDeps = package_ids:
        let without_null = builtins.filter (x: ! (isNull x)) package_ids;
        in builtins.map (id: crates.${id}) without_null;

    # Trivial function to make package dependencies read nicer
    cfg = condition: package_id:
        if condition then package_id else null;

    # sourceFilter: Filters common temp files and build files
    # TODO(pkolloch): Substitute with gitignore filter
    sourceFilter = name: type:
        let baseName = builtins.baseNameOf (builtins.toString name);
        in ! (
          # Filter out git
          baseName == ".gitignore" ||
          (type == "directory" && baseName == ".git" ) ||

          # Filter out build results
          (type == "directory" && (
            baseName == "target" ||
            baseName == "_site" ||
            baseName == ".sass-cache" ||
            baseName == ".jekyll-metadata" ||
            baseName == "build-artifacts"
            )) ||

          # Filter out nix-build result symlinks
          (type == "symlink" && lib.hasPrefix "result" baseName) ||

          # Filter out IDE config
          (type == "directory" && (
            baseName == ".idea" ||
            baseName == ".vscode"
            )) ||
          lib.hasSuffix ".iml" baseName ||

          # Filter out nix build files
          lib.hasSuffix ".nix" baseName ||

          # Filter out editor backup / swap files.
          lib.hasSuffix "~" baseName ||
          builtins.match "^\\.sw[a-z]$" baseName != null ||
          builtins.match "^\\..*\\.sw[a-z]$" baseName != null ||
          lib.hasSuffix ".tmp" baseName ||
          lib.hasSuffix ".bak" baseName
        );

}
